# Disabled temporarily until we can get the workflow to work
name: Test site for publicly known js vulnerabilities

on:
  [workflow_call]
  # workflow_run:
  #   workflows: ['CI'] # runs after CI workflow
  #   types:
  #     - completed

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Test for public javascript library vulnerabilities
        uses: lirantal/is-website-vulnerable@master
        with:
          scan-url: ${{ secrets.SITE_URL }}
